//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOnAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_FoodOnLinkEntities : DbContext
    {
        public DB_FoodOnLinkEntities()
            : base("name=DB_FoodOnLinkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_AdminMaster> TB_AdminMaster { get; set; }
        public virtual DbSet<TB_UserMaster> TB_UserMaster { get; set; }
        public virtual DbSet<TB_AddressConfiguration> TB_AddressConfiguration { get; set; }
        public virtual DbSet<TB_BANNER> TB_BANNER { get; set; }
        public virtual DbSet<TB_CART> TB_CART { get; set; }
        public virtual DbSet<TB_Diningrequest> TB_Diningrequest { get; set; }
        public virtual DbSet<TB_DinningAnswer> TB_DinningAnswer { get; set; }
        public virtual DbSet<TB_EMPLOYEE> TB_EMPLOYEE { get; set; }
        public virtual DbSet<TB_OrderDetails> TB_OrderDetails { get; set; }
        public virtual DbSet<TB_PreferredMenuAnswer> TB_PreferredMenuAnswer { get; set; }
        public virtual DbSet<TB_ProductMaster> TB_ProductMaster { get; set; }
        public virtual DbSet<TB_Restaurant_Images> TB_Restaurant_Images { get; set; }
        public virtual DbSet<TB_RestaurantLike> TB_RestaurantLike { get; set; }
        public virtual DbSet<TB_RestaurantOffersMaster> TB_RestaurantOffersMaster { get; set; }
        public virtual DbSet<TB_Settings> TB_Settings { get; set; }
        public virtual DbSet<TB_VehicalMaster> TB_VehicalMaster { get; set; }
        public virtual DbSet<TB_PreferredMenu> TB_PreferredMenu { get; set; }
        public virtual DbSet<TB_ORDER> TB_ORDER { get; set; }
        public virtual DbSet<TB_SubscriptionMaster> TB_SubscriptionMaster { get; set; }
        public virtual DbSet<TB_PackageMaster> TB_PackageMaster { get; set; }
        public virtual DbSet<TB_PostMaster> TB_PostMaster { get; set; }
        public virtual DbSet<TB_Video_Banner_Image> TB_Video_Banner_Image { get; set; }
        public virtual DbSet<TB_MasterPage_Video_Banner_Image> TB_MasterPage_Video_Banner_Image { get; set; }
        public virtual DbSet<TB_FoodSale_Banner> TB_FoodSale_Banner { get; set; }
        public virtual DbSet<TB_FOOD_CATEGORY> TB_FOOD_CATEGORY { get; set; }
        public virtual DbSet<TB_Restaurant> TB_Restaurant { get; set; }
        public virtual DbSet<TB_ProductCategory> TB_ProductCategory { get; set; }
    }
}
