//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOnAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AddressConfiguration
    {
        public long ADD_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public string APARTMENT { get; set; }
        public string DIRECTION_TO_REACH { get; set; }
        public string OTHER { get; set; }
        public Nullable<long> PINCODE { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    }
}
