//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOnAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DinningAnswer
    {
        public long DA_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<long> RES_ID { get; set; }
        public Nullable<long> DINNING_ID { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
        public Nullable<double> TOTAL_DISCOUNT { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<int> DRINK_DISCOUNT { get; set; }
        public string PAYMENT_STATUS { get; set; }
        public string PAYMENT_AMOUNT { get; set; }
        public string ADVANCED_AMT { get; set; }
        public string ADVANCED_AMOUNT { get; set; }
        public string PAYMENT_PHOTO { get; set; }
    
        public virtual TB_Diningrequest TB_Diningrequest { get; set; }
        public virtual TB_Restaurant TB_Restaurant { get; set; }
        public virtual TB_UserMaster TB_UserMaster { get; set; }
    }
}
