//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOnAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Diningrequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Diningrequest()
        {
            this.TB_DinningAnswer = new HashSet<TB_DinningAnswer>();
        }
    
        public long DINNING_ID { get; set; }
        public string DINNER_TYPE { get; set; }
        public string CHOICE { get; set; }
        public string PREFERENCE { get; set; }
        public string NO_OF_PEOPLE { get; set; }
        public string MINIMUM_BUDGET { get; set; }
        public Nullable<System.DateTime> ARRIVAL_TIME { get; set; }
        public string REMARK { get; set; }
        public string SHOW_MOBILE_NUMBER { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public string ADDRESS { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string REQUEST_TYPE { get; set; }
        public string RESTURANT_LIST { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public string FAMILYRESTRO_TYPE { get; set; }
        public Nullable<System.DateTime> BOOKING_DATE { get; set; }
        public Nullable<System.DateTime> OUT_TIME { get; set; }
        public string PAYMENT_STATUS { get; set; }
        public string MINIMUM_BUDGET_DRINKS { get; set; }
    
        public virtual TB_UserMaster TB_UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DinningAnswer> TB_DinningAnswer { get; set; }
    }
}
