//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOnAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ORDER
    {
        public long ORDER_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<long> RES_ID { get; set; }
        public Nullable<long> ADD_ID { get; set; }
        public Nullable<double> TOTAL_AMOUNT { get; set; }
        public Nullable<long> TOTAL_QUANTITY { get; set; }
        public Nullable<double> DELIVERY_CHARGES { get; set; }
        public Nullable<double> GST { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string DELIVERY_BOY_STATUS { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public string ORDER_TYPE { get; set; }
        public Nullable<long> APP_ORDER_ID { get; set; }
        public string DELIVERY_BOY_REMARK { get; set; }
        public string ORDER_REMARK { get; set; }
        public Nullable<double> ORDER_RATING { get; set; }
        public string RATE_STATUS { get; set; }
    }
}
