//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOnAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PreferredMenuAnswer
    {
        public long PMA_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<long> RES_ID { get; set; }
        public Nullable<long> PreferredMenu_ID { get; set; }
        public Nullable<long> TOTAL_DISCOUNT { get; set; }
        public string REMARK { get; set; }
        public string PAYMENT_STATUS { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<long> TOTAL_AMOUNT { get; set; }
        public Nullable<long> GST { get; set; }
        public Nullable<long> DELIVERY_CHARGES { get; set; }
    }
}
