//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOnAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PackageMaster
    {
        public long P_ID { get; set; }
        public string PACKAGE_NAME { get; set; }
        public string PACKAGE_DESCRIPTION { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> OFFER_PRICE { get; set; }
        public Nullable<long> PACKAGE_VALIDITY { get; set; }
        public Nullable<int> POST_COUNT { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    }
}
