//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOnAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PreferredMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PreferredMenu()
        {
            this.TB_ORDER = new HashSet<TB_ORDER>();
        }
    
        public long PreferredMenu_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public string PREFERRED_MENU { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<double> LATITIUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public string PREFERRED_TYPE { get; set; }
        public string RESTO_LIST { get; set; }
        public string SHOW_MOBILE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string DELIVERY_BOY_REMARK { get; set; }
        public string DELIVERY_BOY_STATUS { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public Nullable<long> APP_ORDER_ID { get; set; }
        public string ORDER_REMARK { get; set; }
        public Nullable<double> ORDER_RATING { get; set; }
        public string RATE_STATUS { get; set; }
        public string PAYMENT_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ORDER> TB_ORDER { get; set; }
    }
}
