//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOnAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PostMaster
    {
        public long POST_ID { get; set; }
        public Nullable<long> RES_ID { get; set; }
        public string POST_IMAGE { get; set; }
        public Nullable<byte> PERCENTAGE_OFF { get; set; }
        public Nullable<decimal> AMOUNT_OFF_UPTO { get; set; }
        public Nullable<System.DateTime> POST_START_DATE { get; set; }
        public Nullable<System.DateTime> POST_END_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string OFFER { get; set; }
        public string POST_NAME { get; set; }
    
        public virtual TB_Restaurant TB_Restaurant { get; set; }
    }
}
