//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOnAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Video_Banner_Image
    {
        public long VID_BANNER_ID { get; set; }
        public string VIDEO_NAME { get; set; }
        public string VIDEO_BANNER_URL { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string VIDEO_URL_LINK { get; set; }
        public Nullable<long> RES_ID { get; set; }
    }
}
